import "./globals.css";

import { GoogleTagManager } from '@next/third-parties/google'
import { dir } from 'i18next'

import { languages } from '../i18n/settings'

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export async function generateStaticParams() {
  return languages.map((lng) => ({ lng }))
}

export default function RootLayout({ children,
  params: {
    lng
  }
 }) {
  return (
    <html  lang={lng} dir={dir(lng)}>
      <head>
      <link rel="stylesheet" href="https://unicons.iconscout.com/release/v4.0.8/css/line.css" />
      </head>
      <GoogleTagManager gtmId="GTM-M2V3XV4N" />
      <body>
        {children}
      </body>
    </html>
  );
}
